### ISSUE TITLE
Request: Support for ClickHouse & Postgres DB Support

### ISSUE THREAD

**Issue by tomtom215** [arihantparsoya/dashboard-semantic-layer#4]
Awesome work on this project! I'd like to recommend support for ClickHouse and Postgres DBs. By supporting these two databases, I think you will support most of the data analytics field who would be interested in trying this project out.

**Comment by rgargrajatgarg** [comment]
Hi @tomtom215 thank you for the recommendation. I will soon update the repo to support both Postgres & ClickHouse.

**Comment by gwozdzm** [comment]
Nice project! After adding PostgreSQL support, you can look at FerretDB and build MongoDB compatibility easily:
https://github.com/FerretDB/FerretDB

**Comment by rgargrajatgarg** [comment]
Thank you @gwozdzm , will definitely look into it.

**Comment by rgargrajatgarg** [comment]
Hi @tomtom215, i am happy to share that we have added the basic support for postgres & clickhouse databases. Thank you for your recommendation
